CREATE TABLE Team_Stats (
TeamId    INT
,G        INT
,MP       INT
,FG       INT
,FGA      INT
,FGP      FLOAT
,ThreeP   INT
,ThreePA  INT
,ThreePP  FLOAT
,TwoP     INT
,TwoPA    INT
,TwoPP    FLOAT
,FT       INT
,FTA      INT
,FTP      FLOAT
,ORB      INT
,DRB      INT
,TRB      INT
,AST      INT
,STL      INT
,BLK      INT
,TOV      INT
,PF       INT
,PTS      INT
,PRIMARY KEY(TeamId));
